# Generated by Django 4.2.7 on 2026-06-04 16:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WireSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wire_size_mm2', models.DecimalField(decimal_places=2, max_digits=6, unique=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Wire Size (mm²)')),
                ('max_ampacity', models.IntegerField(help_text='Maximum safe current in amperes', validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(blank=True, help_text='Application and description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Wire Sizes',
                'ordering': ['wire_size_mm2'],
                'indexes': [models.Index(fields=['max_ampacity'], name='core_wiresi_max_amp_1604fa_idx')],
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, help_text='Upload an image of the component', null=True, upload_to='component_images/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='core.category')),
            ],
            options={
                'ordering': ['-date_created'],
                'indexes': [models.Index(fields=['name'], name='core_compon_name_f3d483_idx'), models.Index(fields=['category'], name='core_compon_categor_6b2672_idx')],
            },
        ),
    ]
