# Generated by Django 4.2.7 on 2026-06-04 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplianceLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('voltage', models.DecimalField(decimal_places=2, default=230, max_digits=8)),
                ('power_watts', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_current', models.DecimalField(blank=True, decimal_places=4, editable=False, help_text='Calculated as I = P / V', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appliance_loads', to='core.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
